drop type request_status cascade;
drop type equipment_type cascade;
drop type service_type cascade;
drop type competition_type cascade;
drop type match_status cascade;
drop type compilation_status cascade;
drop trigger new_rating_match on rating_match;
drop trigger new_sandbox_match on sandbox_match;
drop trigger new_rating_round on rating_round;
drop trigger new_match_solution on match_solution;
drop trigger new_storage_record on storage_record;
drop function create_rating_match_trigger;
drop function create_sandbox_match_trigger;
drop function create_rating_round_trigger;
drop function create_match_solution_trigger;
drop function create_storage_record_trigger;
drop function create_base_user;
drop function create_match_player;
drop function create_rule_set;
drop function create_player_state;
drop function create_testing_system_with_rules;
drop function create_solution_compiler;
drop function partake_in_competition;
drop function manage_competition;
drop function create_competition;
drop function create_rating_round;
drop function add_user_solution;
drop function add_simulation_settings;
drop function add_match_settings;
drop function add_match_map;
drop function create_match;
drop function add_match_tick;
drop function add_player_position;
drop function fill_board_on_startup;
drop function make_solution_compiled;
drop function add_rating_round;
drop function find_recent_solution;
drop function start_chess_rating_round;
drop function add_user_results;
drop function end_match;
drop function calculate_participants_elo;
drop function end_rating_match;
drop function create_competition_request;
drop function process_competition_request;
drop function close_competition_request;
drop function create_organization;
drop function sponsor_competition;
drop function create_equipment;
drop function create_storage;
drop function create_storage_record;
drop function close_storage_record;
drop function end_competition;
drop table rules cascade;
drop table player_state cascade;
drop table solution_compiler cascade;
drop table base_user cascade;
drop table organization cascade;
drop table service cascade;
drop table simulation_settings cascade;
drop table organization_representative cascade;
drop table testing_system cascade;
drop table competition cascade;
drop table competition_sponsor cascade;
drop table competition_service cascade;
drop table competition_manager cascade;
drop table competition_participant cascade;
drop table competition_request cascade;
drop table storage cascade;
drop table equipment cascade;
drop table storage_record cascade;
drop table rating_elo cascade;
drop table player_texture cascade;
drop table map_background_sprite cascade;
drop table simulation_map cascade;
drop table front_match_player cascade;
drop table match_log cascade;
drop table match_settings cascade;
drop table match_tick cascade;
drop table solution cascade;
drop table rating_round cascade;
drop table match_result cascade;
drop table match cascade;
drop table rating_match cascade;
drop table sandbox_match cascade;
drop table match_solution cascade;
drop table user_results cascade;
drop table player_position cascade;
