TURN_NUMBER = 5  # 60  # somewhat mean value
COMPETITION_NUMBER = 2
USERS_NUMBER = 10
RATING_ROUNDS_NUMBER = 1
MAX_SOLUTIONS_NUMBER = 10

EQUIPMENT_PIECES_NUMBER = 10
STORAGE_RECORDS_NUMBER = 6
STORAGES_NUMBER = 4
ORGANIZATIONS_NUMBER = 10
