top_companies_2000 = [
    'ICBC',
    'China Construction Bank',
    'Berkshire Hathaway',
    'JPMorgan Chase',
    'Wells Fargo',
    'Agricultural Bank of China',
    'Bank of America',
    'Bank of China',
    'Apple',
    'Toyota Motor',
    'AT&T',
    'Citigroup',
    'Exxon Mobil',
    'General Electric',
    'Samsung Electronics',
    'Ping An Insurance Group',
    'Wal-Mart Stores',
    'Verizon Communications',
    'Microsoft',
    'Royal Dutch Shell',
    'Allianz',
    'China Mobile',
    'BNP Paribas',
    'Alphabet',
    'China Petroleum & Chemical',
    'Total',
    'AXA Group',
    'Daimler',
    'Volkswagen Group',
    'Mitsubishi UFJ Financial',
    'Comcast',
    'Johnson & Johnson',
    'Banco Santander',
    'Bank of Communications',
    'Nestle',
    'UnitedHealth Group',
    'Nippon Telegraph & Tel',
    'ItaГє Unibanco Holding',
    'Softbank',
    'Gazprom',
    'General Motors',
    'China Merchants Bank',
    'IBM',
    'Royal Bank of Canada',
    'Japan Post Holdings',
    'Procter & Gamble',
    'Pfizer',
    'HSBC Holdings',
    'Goldman Sachs Group',
    'Siemens',
    'BMW Group',
    'China Life Insurance',
    'ING Group',
    'Intel',
    'Postal Savings Bank Of China',
    'Sberbank',
    'TD Bank Group',
    'Cisco Systems',
    'Commonwealth Bank',
    'Morgan Stanley',
    'Novartis',
    'Banco Bradesco',
    'Industrial Bank',
    'Ford Motor',
    'Shanghai Pudong Development',
    'CVS Health',
    'Walt Disney',
    'Prudential',
    'Prudential Financial',
    'Oracle',
    'China State Construction Engineering',
    'Citic Pacific',
    'Boeing',
    'Honda Motor',
    'China Minsheng Banking',
    'Westpac Banking Group',
    'Deutsche Telekom',
    'China Citic Bank',
    'Roche Holding',
    'UBS',
    'Bank of Nova Scotia',
    'Rosneft',
    'Amazon.com',
    'PepsiCo',
    'Sumitomo Mitsui Financial',
    'Coca-Cola',
    'United Technologies',
    'Sanofi',
    'Bayer',
    'Mizuho Financial',
    'Zurich Insurance Group',
    'ANZ',
    'BASF',
    'Walgreens Boots Alliance',
    'Nissan Motor',
    'US Bancorp',
    'American Express',
    'Hon Hai Precision',
    'Enel',
    'Merck',
    'National Australia Bank',
    'PetroChina',
    'Unilever',
    'Hyundai Motor',
    'BBVA-Banco Bilbao Vizcaya',
    'Reliance Industries',
    'Charter Communications',
    'SAIC Motor',
    'Chubb',
    'TelefГіnica',
    'AIA Group',
    'SociГ©tГ© GГ©nГ©rale',
    'Dow Chemical',
    'Home Depot',
    'Lloyds Banking Group',
    'Medtronic',
    'Kraft Heinz Company',
    'Saudi Basic Industries',
    'Facebook',
    'Munich Re',
    'Intesa Sanpaolo',
    'Barclays',
    'Rio Tinto',
    'BHP Billiton',
    'CK Hutchison',
    'Anheuser-Busch InBev',
    'Taiwan Semiconductor',
    'Capital One Financial',
    'LukOil',
    'Swiss Re',
    'Amgen',
    'Banco do Brasil',
    'Bank of Montreal',
    'Gilead Sciences',
    'China Communications Construction',
    'Honeywell International',
    'Manulife',
    'Korea Electric Power',
    'Generali Group',
    'Alibaba',
    'KDDI',
    'China Telecom',
    'AbbVie',
    'Tokio Marine Holdings',
    'Iberdrola',
    'EDF',
    'PNC Financial Services',
    'Tencent Holdings',
    'Allergan',
    'China Everbright Bank',
    'Credit Agricole',
    'Lockheed Martin',
    'Time Warner',
    'Duke Energy',
    'Anthem',
    'Vale',
    'Nordea Bank',
    'Express Scripts',
    'United Parcel Service',
    'Aetna',
    'China Shenhua Energy',
    'VINCI',
    'Bank of New York Mellon',
    'Renault',
    'China Railway Group',
    'EADS',
    'China Railway Construction',
    'China Vanke',
    'Jardine Matheson',
    'Qualcomm',
    'Hewlett Packard Enterprise',
    'British American Tobacco',
    'Visa',
    'China Pacific Insurance',
    'MetLife',
    'AstraZeneca',
    'Altria Group',
    'SAP',
    'Costco Wholesale',
    'Travelers',
    'Philip Morris International',
    'Union Pacific',
    'Delta Air Lines',
    'Southern Company',
    'Lowes',
    'National Grid',
    'Legal & General Group',
    'McKesson',
    'Christian Dior',
    'PTT PCL',
    'Dai-ichi Life Insurance',
    'Twenty-First Century Fox',
    'Canadian Imperial Bank',
    'FedEx',
    'GlaxoSmithKline',
    'Deutsche Post',
    '3M',
    'Aflac',
    'Allstate',
    'Hitachi',
    'Brookfield Asset Management',
    'BT Group',
    'NextEra Energy',
    'BlackRock',
    'Continental',
    'MS&AD Insurance',
    'Aviva',
    'Cigna',
    'Phillips 66',
    'Valero Energy',
    'Enbridge',
    'MondelД“z International',
    'McDonalds',
    'ArcelorMittal',
    'East Japan Railway',
    'Itochu',
    'Japan Tobacco',
    'EI du Pont de Nemours',
    'Eli Lilly',
    'Panasonic',
    'Sun Hung Kai Properties',
    'Fiat Chrysler Automobiles',
    'LafargeHolcim',
    'Qatar National Bank',
    'Target',
    'Fresenius',
    'Danaher',
    'Danske Bank',
    'General Dynamics',
    'Reynolds American',
    'Denso',
    'Bristol-Myers Squibb',
    'CRRC',
    'ABB',
    'Exelon',
    'Cathay Financial',
    'Sun Life Financial',
    'Repsol',
    'Kroger',
    'Abbott Laboratories',
    'HCA Holdings',
    'State Bank of India',
    'DBS Group',
    'Oil & Natural Gas',
    'American Airlines Group',
    'BB&T',
    'Nike',
    'Schneider Electric',
    'Thermo Fisher Scientific',
    'Danone',
    'Samsung Life Insurance',
    'Air Liquide',
    'Huaxia Bank',
    'Orix',
    'Bank of Beijing',
    'HDFC Bank',
    'KBC Group',
    'Deere & Company',
    'Diageo',
    'Central Japan Railway',
    'Liberty Global',
    'Indian Oil',
    'Shinhan Financial Group',
    'Canon',
    'Synchrony Financial',
    'Saint-Gobain',
    'United Continental Holdings',
    'Carnival',
    'HP',
    'Accenture',
    'Country Garden Holdings',
    'State Street',
    'Volvo Group',
    'Inditex',
    'Seven & I Holdings',
    'Mitsubishi Electric',
    'Bridgestone',
    'PG&E',
    'Cardinal Health',
    'Telstra',
    'Dominion Resources',
    'Nomura',
    'Raytheon',
    'Henkel',
    'Marathon Petroleum',
    'Merck',
    'Peugeot',
    'Tata Motors',
    'Archer Daniels Midland',
    'CNP Assurances',
    'Natixis',
    'China Huarong Asset Management',
    'Imperial Tobacco Group',
    'BCE',
    'Northrop Grumman',
    'LyondellBasell Industries',
    'Posco',
    'Telecom Italia',
    'Oversea-Chinese Banking',
    'KB Financial Group',
    'Charles Schwab',
    'Orange',
    'Surgutneftegas',
    'Sompo',
    'Gas Natural Fenosa',
    'WPP',
    'Bank Of Shanghai',
    'ICICI Bank',
    'Poly Real Estate',
    'Hyundai Mobis',
    'DNB',
    'Philips',
    'AmerisourceBergen',
    'Heineken Holding',
    'CRH',
    'Discover Financial Services',
    'Safran',
    'Etisalat',
    'CaixaBank',
    'Eaton',
    'Fubon Financial',
    'Sumitomo',
    'SunTrust Banks',
    'Greenland Holdings Group',
    'China Cinda Asset Management',
    'Anglo American',
    'China Resources Land',
    'Royal Ahold Delhaize N.V.',
    'SingTel',
    'United Overseas Bank',
    'Subaru',
    'Automatic Data Processing',
    'Midea Group',
    'Linde',
    'KIA Motors',
    'Hartford Financial Services',
    'Southwest Airlines',
    'AmГ©rica MГіvil',
    'Principal Financial Group',
    'Fannie Mae',
    'Ameriprise Financial',
    'Macquarie Group',
    'Carrefour',
    'Celgene',
    'China Evergrande Group',
    'Takeda Pharmaceutical',
    'SK Hynix',
    'Saudi Telecom',
    'Tyson Foods',
    'Sinohydro Group',
    'Reckitt Benckiser Group',
    'CSX',
    'Freddie Mac',
    'Lincoln National',
    'Kinder Morgan',
    'Power Corp of Canada',
    'BP',
    'Chevron',
    'Michelin Group',
    'Cheung Kong Property Holdings',
    'SK Holdings',
    'Gree Electric Appliances',
    'BAE Systems',
    'Bank Of Jiangsu',
    'Edison International',
    'Kansai Electric Power',
    'New China Life Insurance',
    'Starbucks',
    'Centrica',
    'Biogen',
    'Canadian National Railway',
    'HDFC',
    'Novo Nordisk',
    'Swedbank',
    'Tata Consultancy Services',
    'Monsanto',
    'Mastercard',
    'Femsa',
    'PayPal',
    'Progressive',
    'Svenska Handelsbanken',
    'Mitsui Fudosan',
    'SEB',
    'Bank Rakyat Indonesia',
    'Texas Instruments',
    'Wilmar International',
    'Daiwa House Industry',
    'Baidu',
    'Consolidated Edison',
    'Maybank',
    'DISH Network',
    'Citic Securities',
    'American Electric',
    'Suzuki Motor',
    'VTB Bank',
    'Metallurgical Corp of China',
    'Petrobras',
    'Norfolk Southern',
    'TJX Cos',
    'Investor AB',
    'American International Group',
    'Sempra Energy',
    'International Airlines',
    'SSE',
    'eBay',
    'NTPC',
    'Old Mutual',
    'Magna International',
    'China Yangtze Power',
    'NN Group',
    'Sumitomo Mitsui Trust',
    'General Mills',
    'Talanx',
    'The Priceline Group',
    'EXOR',
    'Glencore International',
    'Vodafone',
    'Huaneng Power International',
    'Standard Bank Group',
    'Swiss Life Holding',
    'FirstRand',
    'Sysco',
    'International Paper',
    'Vivendi',
    'Kimberly-Clark',
    'National Commercial Bank',
    'Erste Group Bank',
    'Baoshan Iron & Steel',
    'Eni',
    'Saudi Electricity',
    'Corning',
    'Daikin Industries',
    'Mitsubishi Chemical',
    'Becton Dickinson',
    'SK Innovation',
    'Humana',
    'Emerson Electric',
    'Nippon Steel & Sumitomo Metal',
    'Deutsche Bank',
    'Toyota Industries',
    'Pernod Ricard',
    'Aon',
    'IntercontinentalExchange',
    'Stryker',
    'Fujifilm Holdings',
    'Fosun International',
    'Sony',
    'Chubu Electric Power',
    'Las Vegas Sands',
    'Xcel Energy',
    'Fifth Third Bancorp',
    'Bouygues',
    'ENGIE',
    'Steinhoff International',
    'Wheelock',
    'Marsh & McLennan',
    'CBS',
    'Fujitsu',
    'Statoil',
    'Wesfarmers',
    'Axis Bank',
    'HeidelbergCement',
    'Illinois Tool Works',
    'Formosa Petrochemical',
    'Marriott International',
    'Adidas',
    'CLP Holdings',
    'Thomson Reuters',
    'Kering',
    'Colgate-Palmolive',
    'Richemont',
    'Shin-Etsu Chemical',
    'Mapfre',
    'Poste Italiane',
    'Aisin Seiki',
    'Mitsubishi',
    'Mitsubishi Estate',
    'PPL',
    'Waste Management',
    'Micron Technology',
    'Larsen & Toubro',
    'Aegon',
    'Teva Pharmaceutical',
    'Compass Group',
    'Suncor Energy',
    'EDP-Energias de Portugal',
    'Syngenta',
    'Tenaga Nasional',
    'Credit Suisse Group',
    'Hana Financial Group',
    'Sampo',
    'Bank Mandiri',
    'Schlumberger',
    'UniCredit Group',
    'M&T Bank',
    'Thales',
    'Applied Materials',
    'Royal Bank of Scotland',
    'SK Telecom',
    'TE Connectivity',
    'Caterpillar',
    'China Merchants Shekou Industrial Zone Holdings',
    'Ecolab',
    'H&M',
    'Omnicom Group',
    'Chinatrust Financial',
    'Komatsu',
    'Haitong Securities',
    'Grupo ACS',
    'Resona Holdings',
    'Bharti Airtel',
    'Deutsche Lufthansa',
    'Al Rajhi Bank',
    'Swisscom',
    'Couche Tard',
    'Loews',
    'ConocoPhillips',
    'Baxter International',
    'Praxair',
    'Kyocera',
    'Garanti Bank',
    'China Unicom',
    'CIC Group',
    'Kubota',
    'Isbank',
    'Astellas Pharma',
    'CNOOC',
    'Simon Property Group',
    'ASML Holding',
    'British Sky Broadcasting',
    'Cummins',
    'China Zheshang Bank',
    'Standard Chartered',
    'Tokyo Electric Power',
    'Cognizant Technology',
    'Viacom',
    'Sasol',
    'Public Service Enterprise Group',
    'Coal India',
    'Novatek',
    'Kirin Holdings',
    'T&D Holdings',
    'Mitsui',
    'Regions Financial',
    'Ingersoll Rand',
    'CenturyLink',
    'Bank of Nanjing',
    'Dongfeng Motor Group',
    'Citizens Financial Group',
    'Swire Pacific',
    'RELX Group',
    'Samsung Fire & Marine',
    'Associated British Foods',
    'Standard Life',
    'Ally Financial',
    'MГёller-Maersk',
    'Ecopetrol',
    'National Bank of Canada',
    'Sumitomo Electric',
    'Shire',
    'Akzo Nobel',
    'Bank Central Asia',
    'Marubeni',
    'DTE Energy',
    'KoГ§ Holding',
    'Unum',
    'Best Buy',
    'Atlas Copco',
    'MTR',
    'Suncorp Group',
    'Emirates NBD',
    'LG Chem',
    'QBE Insurance Group',
    'Northern Trust',
    'CME Group',
    'Otsuka Holding',
    'Altice',
    'American Tower',
    'Sinopharm Group',
    'Falabella',
    'Bharat Petroleum',
    'Newell Brands',
    'Akbank',
    'Norilsk Nickel',
    'Atlantia',
    'Tesco',
    'MGM Resorts',
    'Dollar Tree',
    'GFNorte',
    'Broadcom',
    'Woori Bank',
    'Guotai Junan Securities',
    'Constellation Brands',
    'Royal Caribbean Cruises',
    'Air Products & Chemicals',
    'Infosys',
    'BYD',
    'KeyCorp',
    'Johnson Controls International',
    'Asahi Kasei',
    'New World Development',
    'Siam Cement',
    'Toray Industries',
    'Grupo Mexico',
    'E.ON',
    'Dell Technologies',
    'Nokia',
    'EletrobrГЎs',
    'Legend Holding',
    'Dollar General',
    'Banco de Sabadell',
    'Eversource Energy',
    'China Taiping Insurance',
    'Hyundai Heavy Industries',
    'Sekisui House',
    'Siam Commercial Bank',
    'China Eastern Airlines',
    'Cemex',
    'Sumitomo Realty',
    'Murata Manufacturing',
    'WEC Energy Group',
    'JXTG Holdings',
    'China Fortune Land Development',
    'Evonik',
    'Henderson Land',
    'China Southern Airlines',
    'ThyssenKrupp Group',
    'Whirlpool',
    'Paccar',
    'Public Bank',
    'Bank of Ningbo',
    'Valeo',
    'Asahi Group Holdings',
    'Unibail-Rodamco',
    'Delphi Automotive',
    'Bunge',
    'Capgemini',
    'Mylan',
    'Sodexo',
    'Kasikornbank',
    'TELUS',
    'Formosa Chemicals',
    'Kao Corp',
    'VMware',
    'Kweichow Moutai',
    'SCA',
    'Fidelity National Information',
    'Aeon',
    'Centene',
    'Great Wall Motor',
    'Telkom Indonesia',
    'Molson Coors Brewing',
    'Naspers',
    'Stanley Black & Decker',
    'Nucor',
    'Transneft',
    'JD.com',
    'National Bank of Abu Dhabi',
    'West Japan Railway',
    'DaVita',
    'Commerzbank',
    'Fortescue Metals Group',
    'Nan Ya Plastics',
    'Solvay',
    'Longfor Properties',
    'Rogers Communications',
    'Barrick Gold',
    'China Reinsurance Group',
    'CIMB Group Holdings',
    'Krung Thai Bank',
    'Tatneft',
    'WH Group',
    'Kellogg',
    'Recruit Holdings',
    'Fast Retailing',
    'EstГ©e Lauder',
    'Allied Irish Banks',
    'PKN Orlen',
    'BAIC Motor',
    'Mazda Motor',
    'Weyerhaeuser',
    'Woolworths',
    'Dong Energy',
    'Level 3 Communications',
    'Franklin Resources',
    'Nidec',
    'George Weston',
    'Lenovo Group',
    'LG Display',
    'Activision Blizzard',
    'Grupo Aval',
    'All Nippon Airways',
    'Reinsurance Group of America',
    'Tesoro',
    'Samsung C&T',
    'RWE Group',
    'Guosen Securities',
    'TransCanada',
    'Adobe Systems',
    'Teliasonera',
    'Dentsu',
    'Deutsche Boerse',
    'Daiwa Securities',
    'GF Securities',
    'Textron',
    'Mitsubishi Heavy Industries',
    'Republic Services',
    'Ericsson',
    'Isuzu Motors',
    'Anhui Conch Cement',
    'First Data',
    'Vonovia',
    'Telenor',
    'Halliburton',
    'PPG',
    'CGN Power',
    'Bankia',
    'Chunghwa Telecom',
    'Veolia Environnement',
    'Occidental Petroleum',
    'J Sainsbury',
    'Bancolombia',
    'Sherwin-Williams',
    'NVIDIA',
    'HAL Trust',
    'VF',
    'Yum Brands',
    'Qingdao Haier',
    'Prologis',
    'Goodyear',
    'Liberty Interactive',
    'Coca-Cola European Partners',
    'Ross Stores',
    'CNH Industrial',
    'Macys',
    'XL Group',
    'Parker-Hannifin',
    'Sabanci Holding',
    'Annaly Capital Management',
    'Industrial Bank of Korea',
    'Hanwha',
    'Essilor International',
    'Kotak Mahindra Bank',
    'Kyushu Electric Power',
    'Scor',
    'Chongqing Changan Auto',
    'Husky Energy',
    'China Energy Engineering',
    'Abertis',
    'Huatai Securities',
    'Luxottica Group',
    'Teck Resources',
    'Lotte Chemical',
    'Tohoku Electric Power',
    'Western Digital',
    'National Bank of Kuwait',
    'Rolls-Royce Holdings',
    'Japan Airlines',
    'Credicorp',
    'UPM-Kymmene',
    'Guangdong Wens Foodstuffs Group',
    'Toyota Tsusho',
    'Wipro',
    'Hilton',
    'Daqin Railway',
    'Lennar',
    'Ferrovial',
    'Anadarko Petroleum',
    'Scentre Group',
    'AutoZone',
    'Agrium',
    'Vestas Wind Systems',
    'China Resources Power',
    'Freeport-mcmoran',
    'Samba Financial Group',
    'ROSSETI',
    'Schaeffler',
    'GD Power Development',
    'Adecco',
    'Discovery Communications',
    'Canadian Natural Resources',
    'Ryanair Holdings',
    'Huntington Bancshares',
    'Hong Kong Exchanges',
    'Carlsberg',
    'Porsche Automobil Holding',
    'Kone',
    'CarMax',
    'ItaГєsa',
    'Sime Darby',
    'Wolseley',
    'Air France-KLM',
    'Willis Towers Watson',
    'Welltower',
    'ITC',
    'KT Corp',
    'OMV Group',
    'Sumitomo Chemical',
    'Emaar Properties',
    'VEON',
    'Eiffage',
    'Bangkok Bank',
    'Metro Group',
    'CSL',
    'Hindustan Petroleum',
    'DR Horton',
    'Leonardo',
    'Shenwan Hongyuan Group',
    'LG Electronics',
    'Kuehne + Nagel',
    'FirstEnergy',
    'Magnit',
    'S&P Global',
    'Chongqing Rural Bank',
    'Toshiba',
    'General Growth Properties',
    'JFE Holdings',
    'Netease',
    'LabCorp',
    'ATOS',
    'Fanuc',
    'SM Investments',
    'Hyundai Steel',
    'Eastman Chemical',
    'L Brands',
    'First Republic Bank',
    'S-Oil',
    'EOG Resources',
    'Secom',
    'LG Corp',
    'Abu Dhabi Commercial Bank',
    'HermГЁs International',
    'Link REIT',
    'TD Ameritrade Holding',
    'Sanlam',
    'Daiichi Sankyo',
    'Norsk Hydro',
    'Williams',
    'Guangzhou Automobile Group',
    'American Financial Group',
    'NXP Semiconductors',
    'China National Nuclear Power',
    'Athene Holding',
    'Woodside Petroleum',
    'Boston Scientific',
    'Raiffeisen Bank International',
    'AMP',
    'Formosa Plastics',
    'China Steel',
    'Bank of Ireland',
    'China Gezhouba',
    'BГўloise Group',
    'Rakuten',
    'Ameren',
    'Symantec',
    'Yara International',
    'Assa Abloy',
    'Shengjing Bank',
    'Aena',
    'Mega Financial Holding',
    'Shanghai International Port',
    'Tokyo Gas',
    'Mohawk Industries',
    'Ooredoo Telecom',
    'China Galaxy Securities',
    'Unipol Gruppo',
    'Quanta Computer',
    'Lam Research',
    'China Merchants Securities',
    'Bank of Jinzhou',
    'Entergy',
    'Canadian Pacific Railway',
    'JM Smucker',
    'NEC',
    'Kingfisher',
    'Lear',
    'Taisei',
    'Kajima',
    'Sandvik',
    'DP World',
    'Pegatron',
    'Power Grid of India',
    'Obayashi',
    'Zimmer Biomet',
    'Devon Energy',
    'Hormel Foods',
    'Julius Baer Group',
    'S.f. Holding',
    'Schindler Holding',
    'Avalonbay Communities',
    'Cencosud',
    'JBS',
    'Uniper',
    'Suning Appliance',
    'Yahoo!',
    'L3 Technologies',
    'CEZ Group',
    'PKO Bank Polski',
    'Alliance Data Systems',
    'AerCap Holdings',
    'Genuine Parts',
    'Fortis (Canada)',
    'Infineon Technologies',
    'Klepierre',
    'Randstad Holding',
    'Skanska',
    'Raymond James Financial',
    'Gemdale',
    'Invesco',
    'DSM',
    'Ageas',
    'Zhejiang Zheneng Electric Power',
    'Mahindra & Mahindra',
    'Swatch Group',
    'Huishang Bank',
    'Vornado Realty',
    'Everest Re Group',
    'Bank Hapoalim',
    'Shimao Property Holdings',
    'Saudi British Bank',
    'Bank Negara Indonesia',
    'Inner Mongolia Yili',
    'Asr Nederland',
    'Beiersdorf',
    'Sharp',
    'Salesforce.com',
    'Aluminum Corp of China',
    'Mercantil Servicios',
    'Halkbank',
    'Guangzhou R&F',
    'Tesla',
    'Tokyu',
    'Neste Oil',
    'CMS Energy',
    'Conagra Brands',
    'China Shipbuilding Industry',
    'Jeronimo Martins',
    'Fairfax Financial',
    'Westfield',
    'Keyence',
    'Banque Saudi Fransi',
    'Towngas',
    'Galaxy Entertainment',
    'WR Berkley',
    'CapitaLand',
    'Shimizu',
    'Snam',
    'VakifBank',
    'Baker Hughes',
    'Onex',
    'Publicis Groupe',
    'Hershey',
    'CenterPoint Energy',
    'HCL Technologies',
    'Riyad Bank',
    'TUI',
    'BOE Technology Group',
    'UC Rusal',
    'Idemitsu Kosan',
    'WestRock',
    'Deutsche Wohnen',
    'Public Storage',
    'Mebuki Financial Group',
    'Comerica',
    'Voya Financial',
    'Arch Capital Group',
    'Daito Trust Construction',
    'Fiserv',
    'Ventas',
    'CBRE Group',
    'Huadian Power International',
    'Markel',
    'Fidelity National Financial',
    'Inpex',
    'Leucadia National',
    'China Coal Energy',
    'Ultrapar Participacoes',
    'Bank Of Hangzhou',
    'Electronic Arts',
    'Fortive',
    'CP All',
    'Amphenol',
    'Regeneron Pharmaceuticals',
    'Mediobanca',
    'Asahi Glass',
    'Universal Health',
    'Mediatek',
    'Singapore Airlines',
    'Banco BTG Pactual Participations',
    'Suntory Beverage & Food',
    'Shanghai Pharmaceuticals',
    'Netflix',
    'CGI Group',
    'Gap',
    'Hankyu Hanshin Holdings',
    'Dr Pepper Snapple Group',
    'Cincinnati Financial',
    'Dongbu Insurance',
    'Power Assets Holdings',
    'Bank of East Asia',
    'Harris',
    'YPF',
    'Finatis',
    'Nielsen',
    'Novolipetsk Steel',
    'Kuwait Finance House',
    'China Grand Automotive Services',
    'EnBW-Energie Baden',
    'Dubai Islamic Bank',
    'Hikvision',
    'Navient',
    'South32',
    'Tokyo Electron',
    'BDO Unibank',
    'Kohl',
    'MTN Group',
    'WW Grainger',
    'Severstal',
    'Sun Pharma Industries',
    'Weichai Power',
    'Arrow Electronics',
    'Grupa PZU',
    'PTT Global Chemical',
    'Bank Leumi',
    'China Resources Pharmaceutical Group',
    'Geely Automobile Holdings',
    'Insurance Australia Group',
    'E-Trade Financial',
    'Nintendo',
    'Stora Enso',
    'BBMG',
    'Seagate Technology',
    'TDK',
    'Uni-President',
    'Rockwell Automation',
    'Henry Schein',
    'Meiji Holdings',
    'Intuit',
    'Lixil Group',
    'London Stock Exchange',
    'Amadeus IT Group',
    'Arconic',
    'Zoetis',
    'Helvetia Holding',
    'Advanced Semiconductor',
    'Yamaha Motor',
    'Alleghany',
    'Crown Castle International',
    'ZTE',
    'Grupo Inbursa',
    'Inter Rao',
    'Newmont Mining',
    'AES',
    'Oneok',
    'Schroders',
    'C.H. Robinson',
    'Quest Diagnostics',
    'Mitsubishi UFJ Lease',
    'Expedia',
    'Boston Properties',
    'Beijing Enterprises',
    'Restaurant Brands International',
    'Analog Devices',
    'Liberty Expedia Holdings',
    'KPN',
    'GS Holdings',
    'OTP Bank',
    'Roper Industries',
    'Host Hotels & Resorts',
    'Asustek Computer',
    'Interpublic Group',
    'QuintilesIMS',
    'Tata Steel',
    'Bankinter',
    'Campbell Soup',
    'Osaka Gas',
    'First Financial Holding',
    'Lotte Shopping',
    'Vienna Insurance Group',
    'SMC',
    'Investec',
    'Power Finance',
    'Voestalpine',
    'Hydro One',
    'Whole Foods Market',
    'Japan Exchange Group',
    'Fortum',
    'Grupo Bimbo',
    'Alrosa',
    'China National Building',
    'Saputo',
    'Shanghai Construction',
    'Mondi',
    'Shin Kong Financial',
    'SDIC Power Holdings',
    'Land Securities Group',
    'China Hongqiao Group',
    'Clorox',
    'Cielo',
    'Assurant',
    'TCL Corp',
    'Wuliangye Yibin',
    'Thai Beverage',
    'Zions Bancorp',
    'National Oilwell Varco',
    'Flextronics International',
    'Hainan Airlines',
    'Yanzhou Coal Mining',
    'Shanghai Electric Group',
    'Xiamen C&D',
    'Lend Lease Group',
    'T Rowe Price',
    'Pgnig Group',
    'Galp Energia',
    'Shenzhen Overseas',
    'Kerry Group',
    'Celanese',
    'Experian',
    'Legrand',
    'Datang International Power',
    'HCP',
    'SES',
    'AGNC Investment',
    'Bank of Tianjin',
    'Phoenix Group Holdings',
    'Harbin Bank',
    'Alaska Air Group',
    'Cenovus Energy',
    'Apache',
    'Delta Electronics',
    'Electrolux Group',
    'Hyundai Marine & Fire',
    'Korea Gas',
    'Keppel',
    'Wm Morrison Supermarkets',
    'AntarChile',
    'SGS',
    'Hyundai Engineering',
    'Toppan Printing',
    'Actelion',
    'Bank of Baroda',
    'Canadian Tire',
    'Intuitive Surgical',
    'Punjab National Bank',
    'Charoen Pokphand Foods',
    'Renesas Electronics',
    'JG Summit Holdings',
    'Ball',
    'Olympus',
    'Sun Art Retail Group',
    'BCI-Banco Credito',
    'CDW',
    'Hesteel',
    'Brown-Forman',
    'Sika',
    'Hoya',
    'SVB Financial Group',
    'Genworth Financial',
    'Cerner',
    'Foot Locker',
    'Mitsubishi Materials',
    'Interactive Brokers Group',
    'Monster Beverage',
    'Dover',
    'Intact Financial',
    'Global Logistic Properties',
    'Skyworks Solutions',
    'Terna',
    'Tokyo Century',
    'Autoliv',
    'Hindalco Industries',
    'Advance Auto Parts',
    'Ayala',
    'Paychex',
    'Rockwell Collins',
    'Oriental Land',
    'Industrial Alliance Insurance',
    'Attijariwafa Bank',
    'American Water Works',
    'Motorola Solutions',
    'United Rentals',
    'Norwegian Cruise Line Holdings',
    'Harley-Davidson',
    'Hess',
    'Masraf Al Rayan',
    'Jiangsu Yanghe Brewery',
    'Grifols',
    'Orient Securities',
    'Mitsubishi Motors',
    'Origin Energy',
    'Qantas Airways',
    'Advanced Info Service',
    'Pentair',
    'Industries Qatar',
    'Nitto Denko',
    'Arab National Bank',
    'Zijin Mining Group',
    'Ricoh',
    'Xerox',
    'Tenet Healthcare',
    'SCANA',
    'Jiangxi Copper',
    'Givaudan',
    'Liberty Broadband',
    'Chiba Bank',
    'Everbright Securities',
    'Smith & Nephew',
    'UCB',
    'Industrivarden',
    'PVH',
    'ALFA',
    'Avnet',
    'Lundbergs',
    'NRG Energy',
    'Shionogi',
    'Csc Financial',
    'New York Community',
    'Naver',
    'LARGAN Precision',
    'Yum China Holdings',
    'Banco De Venezuela',
    'CJ Corp',
    'CA',
    'Top Frontier Investment Holdings',
    'Qatar Islamic Bank',
    'Canara Bank',
    'Mosaic',
    'Shinsei Bank',
    'Braskem',
    'Rural Electrification',
    'Alexion Pharmaceuticals',
    'Aramark',
    'Bank of Zhengzhou',
    'Manpower',
    'Yes Bank',
    'Dexia',
    'Masco',
    'Torchmark',
    'Proximus',
    'X5 Retail Group',
    'RSA Insurance Group',
    'Air Canada',
    'KLA-Tencor',
    'Valeant Pharmaceuticals',
    '3i Group',
    'Bank of India',
    'Check Point Software',
    'Taiwan Cooperative Financial',
    'Community Health Systems',
    'Huntington Ingalls Industries',
    'PGE Polska Grupa Energetyczna',
    'Sekisui Chemical',
    'Brenntag',
    'Bombardier',
    'Coty',
    'Genting',
    'Bank Of Guiyang',
    'PotashCorp',
    'W&W-WГјstenrot',
    'Sojitz',
    'Darden Restaurants',
    'Sunac China Holdings',
    'Unicharm',
    'Ctrip.com International',
    'Jyske Bank',
    'China Life Insurance (Taiwan)',
    'Dai Nippon Printing',
    'CIT Group',
    'IndusInd Bank',
    'Banca MPS',
    'Bed Bath & Beyond',
    'Bank of Chongqing',
    'Marathon Oil',
    'East West Bancorp',
    'Nitori Holdings',
    'Yamato Holdings',
    'Cosco Shipping',
    'SKF Group',
    'GAIL India',
    'PulteGroup',
    'Signature Bank',
    'AGL Energy',
    'Latam Airlines',
    'AutoNation',
    'Doosan',
    'Transocean',
    'Hua Nan Financial',
    'KT&G',
    'LKQ',
    'Equity Residential',
    'Amorepacific',
    'Iida Group Holdings',
    'Gecina',
    'Edwards Lifesciences',
    'Medipal Holdings',
    'Bunzl',
    'El Puerto de Liverpool',
    'Vicinity Centres',
    'Delta Lloyd',
    'Eisai',
    'Marks & Spencer',
    'Pioneer Natural Resources',
    'Arab Bank',
    'FonciГЁre des RГ©gions',
    'Sino-Ocean Land Holdings',
    'Nippon Express',
    'Dxc Technology',
    'Nordstrom',
    'Pandora',
    'GKN',
    'Ajinomoto',
    'BNK Financial Group',
    'Founder Securities',
    'Vedanta Resources',
    'Petronas Chemicals',
    'Magnitogorsk Iron & Steel',
    'Cintas',
    'Dassault Systemes',
    'Quinenco',
    'Nippon Yusen',
    'BRF',
    'Hasbro',
    'Illumina',
    'Kawasaki Heavy Industries',
    'Digital Realty Trust',
    'Alcoa',
    'Chugoku Electric Power',
    'Koito Manufacturing',
    'AmTrust Financial Services',
    'Juniper Networks',
    'United Utilities',
    'Red ElГ©ctrica',
    'RusHydro',
    'Kobe Steel',
    'Wyndham Worldwide',
    'MOL Hungarian Oil',
    'Cathay Pacific Airways',
    'JetBlue Airways',
    'Agilent Technologies',
    'Wolters Kluwer',
    'Arkema',
    'Ezdan Holding Group',
    'JSW Steel',
    'Electric Power Development',
    'Hexagon',
    'Ahli United Bank',
    'Kerry Properties',
    'Yuanta Financial Holding',
    'Airports of Thailand',
    'CR Bard',
    'Hanwha Chemical',
    'Noble Group',
    'Frontier Communications',
    'Ulta Salon Cosmetcs & Fragrance',
    'Crown Holdings',
    'Kintetsu',
    'Starwood Property Trust',
    'Arthur J. Gallagher',
    'Johnson Matthey',
    'UGI',
    'Grupo Televisa',
    'JB Hunt Transport',
    'Iliad',
    'Next',
    'Arca Continental',
    'Uralkali',
    'Xilinx',
    'AAC Technologies Holdings',
    'Gudang Garam',
    'Banco Davivienda',
    'Mead Johnson Nutrition',
    'Essex Property Trust',
    'Amcor',
    'DCC',
    'Geberit',
    'Alfresa Holdings',
    'Mitsui OSK Lines',
    'ICA Gruppen',
    'E.Sun Financial',
    'Fluor',
    'Saudi Arabian Mining',
    'Partners Group Holding',
    'Mashreq Bank',
    'Noble Energy',
    'Caltex Australia',
    'Bank Audi',
    'LG Household & Health Care',
    'Colruyt',
    'Focus Media Information Technology',
    'OMRON',
    'Tenaris',
    'Old Republic International',
    'Fukuoka Financial Group',
    'Baiyin Nonferrous Group',
    'Dentsply Sirona',
    'Tractor Supply',
    'Grupo Carso',
    'Materials Industry Zhongda Group',
    'Almarai',
    'Open Text',
    'RHB Bank',
    'Targa Resources',
    'Taylor Wimpey',
    'Banca Mediolanum',
    'Expeditors International',
    'Inner Mongolia Baotou Steel',
    'Metro',
    'Stockland Australia',
    'Olam International',
    'Pinnacle West',
    'Chang Hwa Bank',
    'Samsung SDS',
    'Brambles',
    'Verisk Analytics',
    'Sealed Air',
    'Union Bank of India',
    'British Land',
    'Seiko Epson',
    'Barratt Developments',
    'NSK',
    'Equifax',
    'Transurban Group',
    'Perrigo',
    'Rite Aid',
    'Coloplast',
    'Newcrest Mining',
    'China Merchants Holdings',
    'Dassault Aviation',
    'UBI Banca',
    'Bajaj Auto',
    'Sabesp',
    'Steel Dynamics',
    'Ramsay Health Care',
    'Equinix',
    'Coach',
    'Cosmo Energy Holdings',
    'ISS',
    'Coca-Cola HBC',
    'Goodman Group',
    'Aeroports de Paris',
    'E-mart',
    'RiseSun Real Estate Development',
    'China National Chemical',
    'Acciona',
    'Fastenal',
    'Hyundai Glovis',
    'Hanesbrands',
    'Penske Automotive',
    'Shoprite Holdings',
    'Gjensidige Forsikring',
    'McCormick',
    'Shanghai Commercial & Savings Bank',
    'Shiseido',
    'AVIC Capita',
    'Melco International Development',
    'Citrix Systems',
    'Goldcorp',
    'Realty Income',
    'AECOM Technology',
    'ITV',
    'Cheniere Energy',
    'Banco Popular Espanol',
    'Agile Property Holdings',
    'NCC Group',
    'Oji Holdings',
    'Korean Air',
    'Hong Leong Financial',
    'Smurfit Kappa Group',
    'Abu Dhabi Islamic Bank',
    'Hyosung',
    'Aozora Bank',
    'Ashtead Group',
    'Storebrand',
    'Persimmon',
    'Ingredion',
    'KB Insurance',
    'Sistema',
    'Taishin Financial Holdings',
    'Yamaguchi Financial',
    'Mizrahi Tefahot Bank',
    'Meritz Financial Group',
    'Kangmei Pharmaceutical',
    'IHI',
    'Scripps Networks Interactive',
    'Hang Lung Group',
    'Waters',
    'SEIBU',
    'China Longyuan Power',
    'Adient',
    'Blom Bank',
    'Hokuhoku Financial Group',
    'Jiangsu Hengrui Medicine',
    'Ametek',
    'STMicroelectronics',
    'Dangote Cement',
    'SDIC Essence',
    'WГ¤rtsilГ¤',
    'Oi',
    'Maxim Integrated Products',
    'Chow Tai Fook Jewellery',
    'Shimano',
    'Bank Muscat',
    'Concordia Financial Group',
    'Thai Oil',
    'Axiata Group',
    'Turkish Airlines',
    'Moscow Exchange',
    'Adani Ports & Special Economic Zone',
    'News Corp',
    'Metalurgica Gerdau',
    'Packaging Corp of America',
    'Oceanwide Holdings',
    'China Communications Services',
    'Hertz Global Holdings',
    'Fresnillo',
    'DSV',
    'Alpha Bank',
    'FleetCor Technologies',
    'IDBI Bank',
    'EMS-Chemie Holding',
    'Whitbread',
    'Albemarle',
    'Taiwan Mobile',
    'NEX Group',
    'Suruga Bank',
    'Compal Electronics',
    'Metropolitan Bank & Trust',
    'Mitsui Chemicals',
    'TransDigm Group',
    'NiSource',
    'Banco BPI',
    'Taiheiyo Cement',
    'Alstom',
    'Liberty Media Corporation Series A Liberty Formula One',
    'Lindt & Sprungli',
    'Continental Resources',
    'Vulcan Materials',
    'MISC',
    'Uniqa',
    'Companhia Brasileira de Distribuicao',
    'Grupo Bolivar',
    'Hiroshima Bank',
    'Yunnan Baiyao Group',
    'Alinma Bank',
    'Ferrari',
    'LG Uplus',
    'Ensco',
    'Assured Guaranty',
    'Banco BPM SpA',
    'EFG International',
    'Rajesh Exports',
    'Wendel',
    'Spirit AeroSystems',
    'Terumo',
    'Office Depot',
    'Shizuoka Bank',
    'Mercuries & Associates',
    'Bank Otkritie',
    'Foshan Haitian Flavouring and Food Company',
    'Staples',
    'Zhengzhou Yutong Bus',
    'Industrial Securities',
    'Pacific Exploration & Production',
    'Ihs Markit',
    'Bendigo & Adelaide Bank',
    'US Foods',
    'CCR',
    'Church & Dwight',
    'Yamada Denki',
    'BCV Group',
    'Hankook Tire',
    'Martin Marietta Materials',
    'Intelsat',
    'Royal Mail',
    'Orkla',
    'Saipem',
    'Aeroflot-Russian Airlines',
    'Westlake Chemical',
    'Canadian Utilities',
    'Suzuken',
    'Concho Resources',
    'Hero Motocorp',
    'Pembina Pipeline',
    'Union National Bank',
    'Gunma Bank',
    'Novozymes',
    'Avis Budget Group',
    'Sumitomo Metal Mining',
    'China International Marine',
    'ONO Pharmaceutical',
    'Maxis',
    'BM&F Bovespa',
    'CNO Financial Group',
    'Piraeus Bank',
    'World Fuel Services',
    'CJ Cheiljedang',
    'Tiffany & Co.',
    'XPO Logistics',
    'BBVA Banco Continental',
    'Tech Data',
    'National Bank of Greece',
    'EasyJet',
    'HRG Group',
    'Kyushu Financial Group',
    'Boliden',
    'NVR',
    'Alliant Energy',
    'Nishi-nippon Financial Holdings',
    'Fortune Brands Home & Security',
    'NetApp',
    'Snap-on',
    'Bank of Qingdao',
    'Far East Horizon',
    'Garmin',
    'North Pacific Bank',
    'Grasim Industries',
    'Banco Comercial Portugues',
    'Moscovskiy Oblastnoi Bank',
    'Rexel',
    'Axis Capital Holdings',
    'Bank of Kyoto',
    'Hachijuni Bank',
    'Guangdong Investment',
    'Chugoku Bank',
    '77 Bank',
    'STRABAG',
    'SBI Holdings',
    'Vietin Bank',
    'GPT Group',
    'Shandong Gold Mining',
    'Jabil Circuit',
    'Sears Holdings',
    'Smiths Group',
    'Eurobank Ergasias',
    'Tsinghua Tongfang',
    'BPER Banca',
    'China Jinmao',
    'Vertex Pharmaceuticals',
    'Dixons Carphone',
    'Incyte',
    'President Chain Store',
    'New Residential Investment',
    'Deutsche Pfandbriefbank',
    'MAp',
    'BorgWarner',
    'Chimera Investment',
    'ProSiebenSat1 Media',
    'Shanghai Lujianzi',
    'Tosoh',
    'Dana Holding',
    'Joint Stock Commercial Bank for Foreign Trade of Vietnam',
    'SL Green Realty',
    'Beijing Shougang',
    'Sysmex',
    'Want Want China',
    'WellCare Health Plans',
    'Catcher Technology',
    'Central Bank of India',
    'Iyo Bank',
    'Mettler-Toledo International',
    'New Hope Liuhe',
    'Wistron',
    'American Equity Investment',
    'Cnpc Capital',
    'Michael Kors Holdings',
    'Ternium',
    'Israel Discount Bank',
    'Signet Jewelers',
    'Empire',
    'PacWest Bancorp',
    'Techtronic Industries',
    'Tokyu Fudosan',
    'Hengan International Group',
    'Moodys',
    'Juroku Bank',
    'AU Optronics',
    'Commercial Bank For Investment & Development Of Vietnam',
    'Shaw Communications',
    'Haseko',
    'Bureau Veritas Registre International de Classific',
    'DSME',
    'CST Brands',
    'Molina Healthcare',
    'Brilliance China Automotive Holdings',
    'Toho Bank',
    'Cattolica Assicurazioni',
    'EQT',
    'Snap',
    'Tongyang Life Insurance',
    'Samsung Heavy Industries',
    'SinoPac Financial',
    'INTL FCStone',
    'Commercial International Bank',
    'Cybg',
    'Orient',
    'Wynn Resorts',
    'Hopson Development Holdings',
    'JTEKT',
    'Nippon Paint',
    'Calpine',
    'BayWa',
    'Migdal Insurance',
    'Changjiang Securities',
    'Aareal Bank',
    'Kansas City Southern',
    'Dufry',
    'Interconexion Electrica',
    'San-In Godo Bank',
    'Nanto Bank',
    'Li & Fung',
    'Lupin',
    'Encana',
    'City Developments',
    'WPG Holdings',
    'KWG Property Holding',
    'Huntsman',
    'Sino Land',
    'Bohai Financial Investment Holding',
    'Tokyo TY Financial Group',
    'Nippon Steel Trading',
    'Bank of Greece',
    'Performance Food Group',
    'Ogaki Kyoritsu Bank',
    'Hyakugo Bank',
    'Daishi Bank',
    'Senshu Ikeda Holdings',
    'Supervalu',
    'NASDAQ OMX Group',
    'CPFL Energia',
    'Severn Trent',
    'PBF Energy',
    'Crown Resorts',
    'Mirae Asset Daewoo',
    'Shiga Bank',
    'SK Networks',
    'Banco de Chile',
    'Showa Shell Sekiyu',
    'Turkcell',
    'Syndicate Bank',
    'Affiliated Managers Group',
    'Vipshop Holdings',
    'Isetan Mitsukoshi Holdings',
    'Taiwan Business Bank',
    'CalAtlantic Group',
    'Waste Connections',
    'NГјrnberger',
    'KION Group',
    'International Flavors & Fragrances',
    'China National Materials',
    'Prada',
    'Indorama Ventures',
    'Korea Zinc',
    'Nomura Research Institute',
    'Tingyi Holding',
    'Tenneco',
    'Cullen/Frost Bankers',
    'First Pacific',
    'Logan Property Holdings',
    'DGB Financial Group',
    'Shanghai Fosun Pharmaceutical (group)',
    'Central Puerto',
    'Xishui Strong Year Ltd. Inner Mongolia',
    'China Mengniu Dairy',
    'Securitas',
    'AmBank Group',
    'Ningbo Port',
    'Penn Virginia',
    'Chongqing New Century Cruise',
    'Jacobs Engineering',
    'Red Star Macalline Group',
    'Virgin Money Holdings',
    'Mattel',
    'Credit Saison',
    'Mirvac Group',
    'Hyakujushi Bank',
    'GameStop',
    'Asian Paints',
    'Frasers Centrepoint',
    'Xiamen Xiangyu',
    'Credito Emiliano',
    'Remgro',
    'Core-Mark Holding Company',
    'Kiyo Bank',
    'Shenzhou International Group Holdings',
    'SYNNEX',
    'Damac Properties',
    'Aboitiz Equity Ventures',
    'HD Supply Holdings',
    'RioCan Real Estate Investment Trust',
    'Emera',
    'Grupo Zuliano',
    'InterContinental Hotels',
    'Impulsora del Desarrollo y el Empleo en America Latina SAB Class B',
    'Accor',
    'Liberbank',
    'Bandai Namco Holdings',
    'Zenith Bank',
    'Fullshare Holdings',
    'Hologic',
    'Keiyo Bank',
    'Banque Centrale Populaire',
    'Owens Corning',
    'Autodesk',
    'Yonghui Superstores',
    'Banca Popolare di Sondrio',
    'VeriSign',
    'Antofagasta',
    'Fuyao Glass Industry Group',
    'Bank of Queensland',
    'Angang Steel',
    'Kingboard Chemical Holdings',
    'Wanhua Chemical Group',
    'Habib Bank',
    'Umicore',
    'Popular',
    'Chesapeake Energy',
    'Golden Agri-Resources',
    'Far Eastern New Century',
    'Musashino Bank',
    'JB Financial Group',
    'Basler Kantonalbank',
    'Indian Overseas Bank',
    'Bid Corp.',
    'Marine Harvest ASA',
    'Nippon Paper Industries',
    'TAQA',
    'United Aircraft',
    'Inventec',
    'Bluescope Steel',
    'Hanwa',
    'Makita',
    'China Railway Signal & Communication',
    'Shanghai Industrial Holdings',
    'Xiamen International Trade Group',
    'Hokkoku Bank',
    'Dali Foods Group',
    'Commercial Bank of Qatar',
    'Industrias PeГ±oles',
    'Allahabad Bank',
    'Avery Dennison',
    'Merlin Properties SOCIMI S.A',
    'Petro Rabigh',
    'Phosagro',
    'UCO Bank',
    'China Molybdenum',
    'NH Investment & Securities',
    'Japan Securities',
    'Corporation Bank',
    'Public Power',
    'Tongling Nonferrous Metals',
    'Zhongsheng Group Holdings',
    'Alawwal Bank',
    'Oriental Bank of Commerce',
    'Paramount Res',
    'Toyota Boshoku',
    'JC Penney',
    'Spectrum Brands Holdings',
    'G4S',
    'Jabal Omar Development',
    'Guoco Group',
    'Two Harbors Investment',
    'Beijing Capital Development',
    'Hellenic Petroleum',
    'Enka',
    'Jilin Jiutai Rural Commercial Bank',
    'Innolux',
    'Luzerner Kantonalbank',
    'China Resources Gas Group',
    'First Quantum Minerals',
    'ST Engineering',
    'Delek Group',
    'Lanxess',
    'Extra Space Storage',
    'Financial Street Holdings',
    'Burberry Group',
    'Petronas Gas',
    'Workday',
    'GS Engineering',
    'Hokkaido Electric Power',
    'Lonza Group',
    'FIBI Holdings',
    'GEA Group',
    'Mid-america Apartment Communities',
    'Vietnam Dairy Products',
    'Sumitomo Rubber',
    'Areva',
    'Leidos',
    'Reliance Steel',
    'Kroton Educacional',
    'Laurentian Bank',
    'Babcock International Group',
    'Fabege AB',
    'First Citizens BancShares',
    'Hella Kgaa Hueck &',
    'BOK Financial',
    'Jazz Pharmaceuticals',
    'Toho Holdings',
    'Microchip Technology',
    'Shanghai International Airport',
    'Atmos Energy',
    'Amdocs',
    'Kuwait Projects',
    'China Aviation Oil',
    'Hakuhodo DY Holdings',
    'MMI Holdings',
    'Chinese Estates',
    'TP ICAP',
    'Technipfmc',
    'Murphy USA',
    'Bank of Nagoya',
    'Emirates Integrated Telecom',
    'St Galler Kantonalbank',
    'Ares Capital',
    'Aroundtown Property Holdings',
    'GOME Electrical Appliances Holding',
    'Greentown China Holdings',
    'Jiangsu Expressway',
    'Premier',
    'China Agri-Industries',
    'Pou Chen',
    'Aldar Properties',
    'Tomony Holdings',
    'Vereit',
    'BioMarin Pharmaceutical',
    'Steel Authority of India',
    'Doha Bank',
    'Jaccs',
    'Indiabulls Housing Finance',
    'Red Hat',
    'Korea Investment Holdings',
    'Indian Bank',
    'Kesko',
    'Minato Bank',
    'Andhra Bank',
    'US Steel',
    'Verbund',
    'Saudi Investment Bank',
    'BMCE Bank',
    'NH Foods',
    'Thomas Cook Group',
    'Manila Electric',
    'Arab Banking',
    'Synovus Financial',
    'Western Union',
    'Pearson',
    'Banca IFIS',
    'Motherson Sumi Systems',
    'SBA Communications',
    'Advanced Micro Devices',
    'Hudsons bay',
    'Total System Services',
    'Sinopec Oilfield Service',
    'Westar Energy',
    'Group 1 Automotive',
    'Dollarama',
    'Shanghai RAAS Blood Products',
    'Associated Banc-Corp',
    'DVB Bank',
    'RenaissanceRe Holdings',
    'Global Payments',
    'Commerce Bancshares',
    'ServiceNow',
    'Samsung SDI',
    'China Great Wall Computer',
    'Tian An China Investments',
    'HollyFrontier',
    'Dah Sing Financial Holdings',
    'Nanya Technology',
    'Shanxi Taigang Stainless',
    'First Horizon National',
    'Brother Industries',
    'Chicago Bridge & Iron',
    'Belle International Holdings',
    'F5 Networks',
    'Valspar',
    'DKSH Holding',
    'Grupo Galicia',
    'Bank of Iwate',
    'Konica Minolta Business Solutions',
    'Synnex Technology Intl',
    'Eurazeo',
    'Bankunited',
    'Barry Callebaut',
    'Inchcape',
    'Yamanashi Chuo Bank',
    'Guangxi Guiguan Electric Power',
    'Live Nation Entertainment',
    'Shaanxi Coal Industry',
    'Aurubis',
    'BEKB-BCBE',
    'Fastighets Balder',
    'Akamai Technologies',
    'Oita Bank',
    'Tech Mahindra']
